module.exports = {
    Matematica: "Matematici",
    Neurologia: "Neurologi",
    Sociologia: "Sociologi",
    Biologia: "Biologi",
    Architettura: "Architetti",
    Archeologia: "Archeologi",
    "Scienze della Formazione": "Scienze della Formazione",
    Rettorato: "Rettorato",
    "Statua della Minerva": "Seguaci della Minerva",
    "Fontana della Minerva": "Seguaci della Minerva",
    Medicina: "Medici",
    Pratone: "Fancazzisti",
    Informatica: "Informatici",
    Chimica: "Chimici",
    "Chimica Industriale": "Chimici Industriali",
    "Aiuola 1": "Fisici",
    "Aiuola 2": "Chimici",
    "Aiuola 3": "Infermieri",
    "Aiuola 4": "Medici",
    "Astrofisica": "Astrofisici",
    "Fisica": "Fisici",
    "Farmacologia": "Studenti di Farmacologia",
    "Igiene": "Studenti di Igene",
    Infermieristica: "Infermieri",
    "Scienze dello Spettacolo": "Studenti di Scienze dello Spettacolo",
    Ortopedia: "Ortopedici",
    Chiesa: "Vaticano",
    Lingue: "Linguisti",
    Zoologia: "Zoologi",
    Geochimica: "Geochimici",
    Mineralogia: "Minerologia",
    Geologia: "Geologi",
    Astronomia: "Astronomi",
    Giurisprudenza: "Giuristi",
    Pratino: "Giuristi",
    "Scienze statistiche": "Studenti di Scienze Statistiche",
    "Scienze Politiche": "Studenti di Scienze Politiche",
    Biotecnologie: "Studenti di Biotecnologie",
    Ostetricia: "Ostetrici",
    Psicologia: "Psicologi",
    Economia: "Studenti di Economia",
    Bar: "Fancazzisti",
    "Ingegneria Informatica": "Ingegneri Informatici",
    "Ingegneria Gestionale": "Studenti di Ingegneria gestionale",
    Genetica: "Studenti di Genetica",
    Botanica: "Studenti di Botanica",
    "Fisica applicata": "Studenti di Fisica Applicata",
    Robotica: "Studenti di Robotica",
    "Chimica analitica": "Studenti di Chimica Analitica",
    "Medicina legale": "Medici Legali",
    "Storia dell'arte": "Storici dell'Arte",
    "Orto Botanico": "Filosofi",
    Lettere: "Studenti di Lettere",
    Filosofia: "Filosofi",
    "Pratino Est 1": "Studenti di Lettere",
    "Pratino Est 2": "Matematici",
    "Ingegneria Civile": "Ingegneri Civili",
    "Ingegneria Edile": "Ingegneri Edili",
    "Ingegneria Chimica": "Ingegneri Chimici",
    "Ingegneria Industriale": "Ingegneri Industriali",
    "Storia": "Storici",
    "Chirurgia": "Chirurghi",
    "Scienze della Comunicazione": "Scienziati della Comunicazione",
    "Pratino Sud":"Scienziati della Comunicazione",
    "Mensa": "Commensali"
}